## C4 - P6

### (Computer Exercise 4.3.4) Write a Python code that implements classical Gramm-Schmidt to find the full $QR$ factorization. Check your work by comparing factorizations of the matices in Exercise 4.3.2.

In [20]:
# import needed libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Magic function to make matplotlib inline; other style specs must come AFTER
%matplotlib inline

# This enables high resolution PNGs.
%config InlineBackend.figure_formats = {'png', 'retina'}

# Some Seaborn settings for notebooks
rc = {'lines.linewidth': 2, 
      'axes.labelsize': 18, 
      'axes.titlesize': 18, 
      'axes.facecolor': 'DFDFE5'}
sns.set_context('notebook', rc=rc)
sns.set_style('darkgrid', rc=rc)

In [21]:
import numpy as np

# class_gramm_schmidt_full : classical Gramm Schmidt, full QR decomposition
# Inputs: matrix a (m x n)
# Output: q (m x m), r (m x n)

def class_gramm_schmidt_full(A):
    (m,n)= A.shape
    R = np.zeros((m,n))
    Q = np.zeros((m,m))
    
# gramm schmidt iteration loop
# for each column of A
    for j in np.arange(n):

# set y equal to the jth column of A, A_j
        y = A[:,j]

# compute projection of A_j onto q_1, q_2, ..., q_{j-1}
# and subtract from y
        for i in np.arange(j):
            R[i,j] = np.dot(Q[:,i],A[:,j])
            y = y - R[i,j]*Q[:,i]

# compute the norm on y
        R[j,j] = np.linalg.norm(y,2)

# construct q_j by normalizing y
        Q[:,j] = y/R[j,j]

# if there are more rows than columns, need m-n more columns in Q
# construct a projection matrix from the current columns of Q that
# projects onto the orthogonal complement of Q, I - Q Q^T
# construct the remaining columns of Q by multiplying I - Q Q^T times
# the first m-n columns of the identity matrix, then normalize the result
    if (m>n):
        P = np.eye(m) - np.dot(Q, Q.transpose())
        tmpQ = P.dot(np.eye(m)[:,0:m-n])
        normQ = np.zeros(m-n)
        for j in np.arange(m-n):
            normQ[j] = np.linalg.norm(tmpQ[:,j])
        Q[:,n:m] = tmpQ/normQ
    return Q,R

### From Exercise 4.3.2 (a) by-hand
### $$A = \begin{bmatrix}2&3\\-2&-6\\1&0\end{bmatrix}$$
### $$Q = \begin{bmatrix}2/3&-1/3&2/3\\-2/3&-2/3&1/3\\1/3&-2/3&-2/3\end{bmatrix}$$
### $$R = \begin{bmatrix}3&6\\0&3\\0&0\end{bmatrix}$$

In [18]:

# matrices form Exercise 4.3.2
a = np.array([[2,3],[-2,-6],[1,0]])
print('a=',a)

q,r = class_gramm_schmidt_full(a)
print('\nq = ', q)
print('\nr = ', r)
print('\nqr = ', q.dot(r))
print('\nqT Q = ', np.dot(q.transpose(),q))

a= [[ 2  3]
 [-2 -6]
 [ 1  0]]

q =  [[ 0.66666667 -0.33333333  0.66666667]
 [-0.66666667 -0.66666667  0.33333333]
 [ 0.33333333 -0.66666667 -0.66666667]]

r =  [[ 3.  6.]
 [ 0.  3.]
 [ 0.  0.]]

qr =  [[ 2.  3.]
 [-2. -6.]
 [ 1.  0.]]

qT Q =  [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### We see that the output of the function class_gramm_schmidt_full() matches the by-hand result.

### From Exercise 4.3.2 (b) by-hand
### $$A = \begin{bmatrix}-4&-4\\-2&7\\4&-5\end{bmatrix}$$
### $$Q = \begin{bmatrix}-2/3&-2/3&1/3\\-1/3&2/3&2/3\\2/3&-1/3&2/3\end{bmatrix}$$
### $$R = \begin{bmatrix}6&-3\\0&9\\0&0\end{bmatrix}$$

In [19]:
# matrices form Exercise 4.3.2
a = np.array([[-4,-4],[-2,7],[4,-5]])
print('a=',a)

q,r = class_gramm_s(a)
print('\nq = ', q)
print('\nr = ', r)
print('\nqr = ', q.dot(r))
print('\nqT Q = ', np.dot(q.transpose(),q))

a= [[-4 -4]
 [-2  7]
 [ 4 -5]]

q =  [[-0.66666667 -0.66666667  0.74535599]
 [-0.33333333  0.66666667 -0.2981424 ]
 [ 0.66666667 -0.33333333  0.59628479]]

r =  [[ 6. -3.]
 [ 0.  9.]
 [ 0.  0.]]

qr =  [[-4. -4.]
 [-2.  7.]
 [ 4. -5.]]

qT Q =  [[  1.00000000e+00  -2.77555756e-17   0.00000000e+00]
 [ -2.77555756e-17   1.00000000e+00  -8.94427191e-01]
 [  0.00000000e+00  -8.94427191e-01   1.00000000e+00]]


### We see that the output of the function class_gramm_schmidt_full() matches the by-hand result.